package soap

import "encoding/xml"

// Envelope represents the root <soapenv:Envelope> tag.
type Envelope struct {
	XMLName xml.Name `xml:"soapenv:Envelope"`
	Xmlns   string   `xml:"xmlns:soapenv,attr"`
	Web     string   `xml:"xmlns:web,attr"`
	Header  *Header  `xml:"soapenv:Header,omitempty"`
	Body    Body
}

// Header is empty but required by the protocol.
type Header struct {
	XMLName xml.Name `xml:"soapenv:Header"`
}

// Body contains the actual function call.
type Body struct {
	XMLName     xml.Name    `xml:"soapenv:Body"`
	GwOperation GwOperation `xml:"web:gwOperation"`
}

// GwOperation maps to the Movitel BCCS Gateway API format.
// The operation name is gwOperation as declared in the WSDL.
type GwOperation struct {
	Input Input `xml:"Input"`
}

// Input wraps the actual payload.
type Input struct {
	Username string  `xml:"username"`
	Password string  `xml:"password"`
	Wscode   string  `xml:"wscode"`
	Params   []Param `xml:"param"`
	RawData  string  `xml:"rawData"` // Can be empty or "?" depending on the call
}

// Param represents a single key-value request parameter.
type Param struct {
	Name  string `xml:"name,attr"`
	Value string `xml:"value,attr"`
}

// ResponseEnvelope represents the envelope returned by Movitel.
type ResponseEnvelope struct {
	XMLName xml.Name     `xml:"Envelope"`
	Body    ResponseBody `xml:"Body"`
}

type ResponseBody struct {
	GwOperationResp GwOperationResponse `xml:"gwOperationResponse"`
}

// GwOperationResponse contains the outer Result tag from Movitel.
// Per the spec, the inner <Result> string contains the transaction-level response.
type GwOperationResponse struct {
	Result string `xml:"Result"`
}

// DetailResponse represents the parsed content of the inner result string.
// These are the transaction-level fields returned per the API specification.
type DetailResponse struct {
	ErrorCode   string `xml:"errorCode"`       // 0 = Success, see detail response code table
	Message     string `xml:"message"`         // Human readable description
	TransID     string `xml:"transId"`         // Transaction ID
	RequestID   string `xml:"requestId"`       // Request ID generated by eMola system (used by callback)
	Balance     string `xml:"balance"`         // Account balance (only on balance queries)
	OrgRespCode string `xml:"orgResponseCode"` // Original response code from backend
}

// NewEnvelope creates a properly formatted SOAP Envelope.
func NewEnvelope(username, password, wscode string, params []Param) *Envelope {
	return &Envelope{
		Xmlns: "http://schemas.xmlsoap.org/soap/envelope/",
		Web:   "http://webservice.bccsgw.viettel.com/", // Correct namespace from WSDL
		Body: Body{
			GwOperation: GwOperation{
				Input: Input{
					Username: username,
					Password: password,
					Wscode:   wscode,
					Params:   params,
					RawData:  "?", // Postman uses "?" or "" for rawData. Using "?" to match withdrawing operations
				},
			},
		},
	}
}
